# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1248787454);
user_pref("app.update.lastUpdateTime.background-update-timer", 1248787454);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1248787454);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1248697473);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1248787454);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1248853164);
user_pref("browser.download.lastDir", "C:\\Dokumente und Einstellungen\\niegel\\Desktop");
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://google.de");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.1");
user_pref("extensions.enabledItems", "jqs@sun.com:1.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.1");
user_pref("extensions.lastAppVersion", "3.5.1");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "us-ascii, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1250671556);
user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1, vmix, bonifax");
