#! /bin/sh
#
# postinst script for opsi-winst-test
# This script executes after unpacking files from that archive and registering the product at the server.
#
# The following environment variables can be used to obtain information about the current installation:
#   PRODUCT_ID: id of the current product
#   CLIENT_DATA_DIR: directory which contains the installed client data
#

chmod ugo+x $CLIENT_DATA_DIR/opsi-script-test-helper-lin/64/*
chmod ugo+x $CLIENT_DATA_DIR/opsi-script-test-helper-mac/*